#ifndef SN_CORELIB_NETWORK_RPC_ABSTRACT_API_BINDER_H
#define SN_CORELIB_NETWORK_RPC_ABSTRACT_API_BINDER_H

#include "corelib/global/global.h"

class SN_CORELIB_EXPORT AbstractApiBinder
{
   
};

#endif // SN_CORELIB_NETWORK_RPC_ABSTRACT_API_BINDER_H
