#ifndef SN_CORELIB_NETWORK_RPC_ABSTRACT_API_PROVIDER_H
#define SN_CORELIB_NETWORK_RPC_ABSTRACT_API_PROVIDER_H

#include "corelib/global/global.h"

class SN_CORELIB_EXPORT AbstractApiProvider
{
   
};

#endif // SN_CORELIB_NETWORK_RPC_ABSTRACT_API_PROVIDER_H
